# Generated by Django 6.1.1 on 2026-09-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_reg_number', models.CharField(max_length=50)),
                ('amount_paid', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer')], max_length=30)),
                ('academic_term', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fee_collections',
                'ordering': ['-created_at'],
            },
        ),
    ]
