# Generated by Django 6.1.1 on 2026-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='expected_fee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
